name: ci-latest

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build_deps:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockertags: [latest]
    container: rclex/rclex_docker:${{ matrix.dockertags }}

    steps:
      - name: Checkout rclex repo
        uses: actions/checkout@v4
        with:
          repository: FelixPe/rclex
          path: rclex

      - name: Retrieve cached dependencies
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: |
            rclex/deps
            rclex/_build
          key: ${{ runner.os }}-${{ matrix.dockertags }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.dockertags }}-mix-

      - name: Build dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex
          mix deps.get
          mix deps.compile

  code-analysis:
    needs: build_deps
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockertags: [latest]
    container: rclex/rclex_docker:${{ matrix.dockertags }}

    steps:
      - name: Checkout rclex repo
        uses: actions/checkout@v4
        with:
          repository: FelixPe/rclex
          path: rclex

      - name: Retrieve cached dependencies
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: |
            rclex/deps
            rclex/_build
          key: ${{ runner.os }}-${{ matrix.dockertags }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.dockertags }}-mix-

      - name: mix format
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex
          mix format --check-formatted

      - name: mix credo
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex
          mix local.hex --force
          mix credo

      - name: Restore PLT cache
        id: plt-cache
        uses: actions/cache/restore@v4
        with:
          key: |
            plt-${{ runner.os }}-${{ matrix.dockertags }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            plt-${{ runner.os }}-${{ matrix.dockertags }}-mix-
          path: |
            rclex/priv/plts

      - name: Create PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex
          mix dialyzer --plt

      - name: Save PLT cache
        id: plt_cache_save
        uses: actions/cache/save@v4
        if: steps.plt-cache.outputs.cache-hit != 'true'
        with:
          key: |
            plt-${{ runner.os }}-${{ matrix.dockertags }}-mix-${{ hashFiles('**/mix.lock') }}
          path: |
            rclex/priv/plts

      - name: mix dialyzer
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex
          mix dialyzer

  test:
    needs: build_deps
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockertags: [latest]
    container: rclex/rclex_docker:${{ matrix.dockertags }}

    steps:
      - name: Checkout rclex repo
        uses: actions/checkout@v4
        with:
          repository: FelixPe/rclex
          path: rclex

      - name: Checkout rclex_connection_tests repo
        uses: actions/checkout@v4
        with:
          repository: rclex/rclex_connection_tests
          path: rclex_connection_tests

      - name: Retrieve cached dependencies
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: |
            rclex/deps
            rclex/_build
          key: ${{ runner.os }}-${{ matrix.dockertags }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.dockertags }}-mix-

      - name: mix compile
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex
          mix local.hex --force
          mix compile --warnings-as-errors

      - name: mix test
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex
          mix rclex.gen.msgs
          mix rclex.gen.srvs
          mix test --warnings-as-errors --cover

      - name: connection tests
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex_connection_tests
          mix local.hex --force
          ./run-all.sh
