on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  rclex_test:
    runs-on: ubuntu-latest
    container: rclex/rclex_docker:latest

    steps:
        # clone latest branch
        - name: clone
          uses: actions/checkout@v2
        - name: clone rclex_connection_tests
          uses: actions/checkout@v2
          with:
            repository: rclex/rclex_connection_tests
            path: rclex_connection_tests
        
        - name: compile
          run: |
            echo 'cd lib'
            cd lib
            echo 'ln -s ../rclex_connection_tests/rclex/lib/test'
            ln -s ../rclex_connection_tests/rclex/lib/test
            echo 'cd ../'
            cd ../
            echo 'mix local.hex --force'
            MIX_ENV=test mix local.hex --force
            echo 'mix deps.get'
            MIX_ENV=test mix deps.get
            echo 'MIX_ENV=test mix compile'
            MIX_ENV=test mix compile

        - name: mix test 
          run: |
            source /opt/ros/dashing/setup.bash
            echo 'mix test'
            mix test

        - name: ros2 connection test
          run: | 
            source /opt/ros/dashing/setup.bash
            cd rclex_connection_tests
            ./entrypoint.sh
            
